export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT='AUTH_LOGOUT'

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'

export const ALERT_MESSAGE = 'ALERT_MESSAGE'


export const FETCH_CATEGORY_START = 'FETCH_CATEGORY_START'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'

export const REDIRECT = 'REDIRECT'