export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT='AUTH_LOGOUT'

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'

export const ALERT_MESSAGE = 'ALERT_MESSAGE'


export const FETCH_CATEGORY_START = 'FETCH_CATEGORY_START'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_BY_ID_START = 'FETCH_CATEGORY_BY_ID_START'
export const FETCH_CATEGORY_BY_ID_SUCCESS = 'FETCH_CATEGORY_BY_ID_SUCCESS'
export const FETCH_CATEGORY_BY_ID_END = 'FETCH_CATEGORY_BY_ID_END'
export const ADD_CATEGORY_SUCCESS ='ADD_CATEGORY_SUCCESS'
export const EDITING_CATEGORY_SUCCESS='EDITING_CATEGORY_SUCCESS'

export const REDIRECT = 'REDIRECT'