export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT='AUTH_LOGOUT'

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'

export const ALERT_MESSAGE = 'ALERT_MESSAGE'


export const CATEGORY_LIST = 'CATEGORY_LIST'

export const REDIRECT = 'REDIRECT'